"""add chat member unique constraint

Revision ID: e7f0d7e4f990
Revises: 56e5abaa83d4
Create Date: 2026-08-24 17:01:22.555896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7f0d7e4f990'
down_revision: Union[str, Sequence[str], None] = '56e5abaa83d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_chat_member', 'chat_member', ['chat_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_chat_member', 'chat_member', type_='unique')
    # ### end Alembic commands ###
